// 多语言字符串表 —— zh 为默认（test/ 按 zh 文案断言，值须与原字面量逐字节一致）。
// en/ja/ko/de/fr 为出海初版译文，欢迎母语用户反馈校正（GitHub Issues/Discussions）。
// 取词 s('key')；含 {n}/{name} 占位符的在调用处 replaceFirst 填值。
// 语言在 main() 按系统语言初始化一次（initStrings），未支持的语言回退英文。
const Map<String, Map<String, String>> kStrings = {
  'zh': {
    'err_access': '无法访问该文件',
    'untitled': '未命名.md',
    'replace_title': '替换同名文件？',
    'replace_msg': '已有「{name}」的记录，替换后内容更新，但旧标注可能因位置变化而错位。',
    'cancel': '取消',
    'replace': '替换',
    'err_import': '导入失败',
    'err_gone': '文件不存在，已从列表移除',
    'deleted': '已删除「{name}」',
    'undo': '撤销',
    'del_title': '删除这条记录？',
    'del_msg': '「{name}」的应用内副本与标注会一并删除。',
    'delete': '删除',
    'clear_title': '清空全部记录？',
    'clear_msg': '所有文件的应用内副本与标注会一并删除，不可恢复。',
    'clear': '清空',
    'cleared': '已清空',
    'home_tagline': '微信里收到的文档，都能舒服地看',
    'open_btn': '打开 .md 文件',
    'empty_title': '还没有文档',
    'empty_hint': '点上面的按钮选择文件；在微信里也可以\n选"用其他应用打开"直接跳到本应用',
    'recent': '最近',
    'built': '构建',
    'err_docx_empty': '未能从文档中提取到文本',
    'err_epub': '未能解析此文件',
    'err_missing': '文件不存在或无法读取',
    'err_encoding': '文件编码无法识别',
    'err_open': '打开失败：文件可能已损坏或格式不受支持',
    'chapter': '第 {n} 章',
    'no_outline_pdf': '此 PDF 无书签（引擎暂不支持）',
    'no_outline': '此文档没有可导航的标题',
    'outline': '目录',
    'search': '搜索',
    'marks': '标注列表',
    'font_smaller': '减小字号',
    'font_bigger': '增大字号',
    'theme_sheet': '背景色',
    'search_hint': '搜索正文…',
    'prev': '上一个',
    'next': '下一个',
    'close_search': '关闭搜索',
    'underline': '划线',
    'highlight': '高亮',
    'copy': '复制',
    'copied': '已复制',
    'marks_count': '标注（{n}）',
    'search_marks': '搜索标注内容…',
    'all': '全部',
    'no_marks': '暂无标注',
    'page_n': '第 {n} 页',
    'theme_light': '浅色',
    'theme_dark': '深色',
    'theme_paper': '纸白',
    'theme_warm': '淡暖',
    'theme_green': '绿豆沙',
    'theme_blue': '淡青',
  },
  'en': {
    'err_access': "Can't access this file",
    'untitled': 'Untitled.md',
    'replace_title': 'Replace file with the same name?',
    'replace_msg':
        'A record for "{name}" already exists. The content will be updated, but old annotations may shift position.',
    'cancel': 'Cancel',
    'replace': 'Replace',
    'err_import': 'Import failed',
    'err_gone': "File no longer exists — removed from the list",
    'deleted': 'Deleted "{name}"',
    'undo': 'Undo',
    'del_title': 'Delete this entry?',
    'del_msg': 'The in-app copy of "{name}" and its annotations will be deleted.',
    'delete': 'Delete',
    'clear_title': 'Clear all entries?',
    'clear_msg': 'All in-app copies and annotations will be deleted. This cannot be undone.',
    'clear': 'Clear',
    'cleared': 'Cleared',
    'home_tagline': 'A proper reading surface for the files your phone throws at you',
    'open_btn': 'Open a document',
    'empty_title': 'No documents yet',
    'empty_hint':
        'Tap the button above to pick a file — or "Open with" MD+ from WhatsApp, Telegram or your email app.',
    'recent': 'Recent',
    'built': 'built',
    'err_docx_empty': 'No text could be extracted from this document',
    'err_epub': 'Could not parse this file',
    'err_missing': "File doesn't exist or can't be read",
    'err_encoding': 'Unrecognized file encoding',
    'err_open': "Couldn't open the file — it may be corrupted or in an unsupported format",
    'chapter': 'Chapter {n}',
    'no_outline_pdf': 'This PDF has no bookmarks (not supported by the engine yet)',
    'no_outline': 'This document has no headings to navigate',
    'outline': 'Contents',
    'search': 'Search',
    'marks': 'Annotations',
    'font_smaller': 'Smaller text',
    'font_bigger': 'Larger text',
    'theme_sheet': 'Background',
    'search_hint': 'Search the text…',
    'prev': 'Previous',
    'next': 'Next',
    'close_search': 'Close search',
    'underline': 'Underline',
    'highlight': 'Highlight',
    'copy': 'Copy',
    'copied': 'Copied',
    'marks_count': 'Annotations ({n})',
    'search_marks': 'Search annotations…',
    'all': 'All',
    'no_marks': 'No annotations yet',
    'page_n': 'Page {n}',
    'theme_light': 'Light',
    'theme_dark': 'Dark',
    'theme_paper': 'Paper',
    'theme_warm': 'Warm',
    'theme_green': 'Green',
    'theme_blue': 'Blue',
  },
  'ja': {
    'err_access': 'ファイルにアクセスできません',
    'untitled': '無題.md',
    'replace_title': '同名のファイルを置き換えますか？',
    'replace_msg': '「{name}」の記録が既にあります。置き換えると内容は更新されますが、以前の注釈は位置がずれる場合があります。',
    'cancel': 'キャンセル',
    'replace': '置き換える',
    'err_import': 'インポートに失敗しました',
    'err_gone': 'ファイルが存在しないため、リストから削除しました',
    'deleted': '「{name}」を削除しました',
    'undo': '元に戻す',
    'del_title': 'この記録を削除しますか？',
    'del_msg': '「{name}」のアプリ内コピーと注釈が一緒に削除されます。',
    'delete': '削除',
    'clear_title': 'すべての記録を消去しますか？',
    'clear_msg': 'すべてのファイルのアプリ内コピーと注釈が一緒に削除され、元に戻せません。',
    'clear': '消去',
    'cleared': '消去しました',
    'home_tagline': 'スマホに届いたファイルを、快適に読む',
    'open_btn': 'ドキュメントを開く',
    'empty_title': 'まだドキュメントがありません',
    'empty_hint': '上のボタンでファイルを選ぶか、WhatsApp・Telegram・メールアプリから「他のアプリで開く」で MD+ を選んでください。',
    'recent': '最近',
    'built': 'ビルド',
    'err_docx_empty': 'ドキュメントからテキストを抽出できませんでした',
    'err_epub': 'このファイルを解析できません',
    'err_missing': 'ファイルが存在しないか、読み取れません',
    'err_encoding': 'ファイルのエンコーディングを認識できません',
    'err_open': '開けませんでした：ファイルが壊れているか、対応していない形式の可能性があります',
    'chapter': '第{n}章',
    'no_outline_pdf': 'この PDF にはしおりがありません（エンジンが未対応）',
    'no_outline': 'このドキュメントには移動できる見出しがありません',
    'outline': '目次',
    'search': '検索',
    'marks': '注釈リスト',
    'font_smaller': '文字を小さく',
    'font_bigger': '文字を大きく',
    'theme_sheet': '背景',
    'search_hint': '本文を検索…',
    'prev': '前へ',
    'next': '次へ',
    'close_search': '検索を閉じる',
    'underline': '下線',
    'highlight': 'ハイライト',
    'copy': 'コピー',
    'copied': 'コピーしました',
    'marks_count': '注釈（{n}）',
    'search_marks': '注釈を検索…',
    'all': 'すべて',
    'no_marks': '注釈はまだありません',
    'page_n': '{n} ページ',
    'theme_light': 'ライト',
    'theme_dark': 'ダーク',
    'theme_paper': 'ペーパー',
    'theme_warm': 'ウォーム',
    'theme_green': 'グリーン',
    'theme_blue': 'ブルー',
  },
  'ko': {
    'err_access': '파일에 접근할 수 없습니다',
    'untitled': '제목 없음.md',
    'replace_title': '같은 이름의 파일을 교체할까요?',
    'replace_msg': '"{name}" 기록이 이미 있습니다. 교체하면 내용이 업데이트되지만 기존 주석의 위치가 어긋날 수 있습니다.',
    'cancel': '취소',
    'replace': '교체',
    'err_import': '가져오기 실패',
    'err_gone': '파일이 더 이상 없어 목록에서 제거했습니다',
    'deleted': '"{name}" 삭제됨',
    'undo': '실행 취소',
    'del_title': '이 기록을 삭제할까요?',
    'del_msg': '"{name}"의 앱 내 사본과 주석이 함께 삭제됩니다.',
    'delete': '삭제',
    'clear_title': '모든 기록을 지울까요?',
    'clear_msg': '모든 파일의 앱 내 사본과 주석이 함께 삭제되며 복구할 수 없습니다.',
    'clear': '지우기',
    'cleared': '지웠습니다',
    'home_tagline': '휴대폰으로 받은 파일을 편안하게 읽어 보세요',
    'open_btn': '문서 열기',
    'empty_title': '아직 문서가 없습니다',
    'empty_hint': "위 버튼으로 파일을 고르거나 WhatsApp·텔레그램·메일 앱에서 '다른 앱으로 열기'로 MD+를 선택하세요.",
    'recent': '최근',
    'built': '빌드',
    'err_docx_empty': '문서에서 텍스트를 추출할 수 없습니다',
    'err_epub': '이 파일을 해석할 수 없습니다',
    'err_missing': '파일이 없거나 읽을 수 없습니다',
    'err_encoding': '파일 인코딩을 인식할 수 없습니다',
    'err_open': '열 수 없습니다: 파일이 손상되었거나 지원하지 않는 형식일 수 있습니다',
    'chapter': '{n}장',
    'no_outline_pdf': '이 PDF에는 책갈피가 없습니다(엔진 미지원)',
    'no_outline': '이 문서에는 이동할 수 있는 제목이 없습니다',
    'outline': '목차',
    'search': '검색',
    'marks': '주석 목록',
    'font_smaller': '글자 작게',
    'font_bigger': '글자 크게',
    'theme_sheet': '배경',
    'search_hint': '본문 검색…',
    'prev': '이전',
    'next': '다음',
    'close_search': '검색 닫기',
    'underline': '밑줄',
    'highlight': '형광펜',
    'copy': '복사',
    'copied': '복사됨',
    'marks_count': '주석({n})',
    'search_marks': '주석 검색…',
    'all': '전체',
    'no_marks': '아직 주석이 없습니다',
    'page_n': '{n}페이지',
    'theme_light': '라이트',
    'theme_dark': '다크',
    'theme_paper': '페이퍼',
    'theme_warm': '웜',
    'theme_green': '그린',
    'theme_blue': '블루',
  },
  'de': {
    'err_access': 'Auf diese Datei kann nicht zugegriffen werden',
    'untitled': 'Unbenannt.md',
    'replace_title': 'Datei mit demselben Namen ersetzen?',
    'replace_msg': 'Für „{name}" existiert bereits ein Eintrag. Der Inhalt wird aktualisiert, aber alte Anmerkungen können verschoben werden.',
    'cancel': 'Abbrechen',
    'replace': 'Ersetzen',
    'err_import': 'Import fehlgeschlagen',
    'err_gone': 'Datei existiert nicht mehr — aus der Liste entfernt',
    'deleted': '„{name}" gelöscht',
    'undo': 'Rückgängig',
    'del_title': 'Diesen Eintrag löschen?',
    'del_msg': 'Die In-App-Kopie von „{name}" und ihre Anmerkungen werden gelöscht.',
    'delete': 'Löschen',
    'clear_title': 'Alle Einträge löschen?',
    'clear_msg': 'Alle In-App-Kopien und Anmerkungen werden gelöscht. Dies kann nicht rückgängig gemacht werden.',
    'clear': 'Alle löschen',
    'cleared': 'Gelöscht',
    'home_tagline': 'Dokumente, die auf Ihrem Handy landen, richtig bequem lesen',
    'open_btn': 'Dokument öffnen',
    'empty_title': 'Noch keine Dokumente',
    'empty_hint': 'Tippen Sie oben auf die Schaltfläche, um eine Datei auszuwählen — oder öffnen Sie Dateien aus WhatsApp, Telegram oder Ihrer E-Mail-App mit „Mit MD+ öffnen".',
    'recent': 'Zuletzt genutzt',
    'built': 'Build',
    'err_docx_empty': 'Aus dem Dokument konnte kein Text extrahiert werden',
    'err_epub': 'Diese Datei konnte nicht gelesen werden',
    'err_missing': 'Datei existiert nicht oder ist nicht lesbar',
    'err_encoding': 'Unbekannte Dateicodierung',
    'err_open': 'Öffnen fehlgeschlagen — die Datei ist möglicherweise beschädigt oder hat ein nicht unterstütztes Format',
    'chapter': 'Kapitel {n}',
    'no_outline_pdf': 'Dieses PDF hat keine Lesezeichen (von der Engine noch nicht unterstützt)',
    'no_outline': 'Dieses Dokument hat keine navigierbaren Überschriften',
    'outline': 'Inhalt',
    'search': 'Suchen',
    'marks': 'Anmerkungen',
    'font_smaller': 'Kleinerer Text',
    'font_bigger': 'Größerer Text',
    'theme_sheet': 'Hintergrund',
    'search_hint': 'Text durchsuchen…',
    'prev': 'Zurück',
    'next': 'Weiter',
    'close_search': 'Suche schließen',
    'underline': 'Unterstreichen',
    'highlight': 'Hervorheben',
    'copy': 'Kopieren',
    'copied': 'Kopiert',
    'marks_count': 'Anmerkungen ({n})',
    'search_marks': 'Anmerkungen durchsuchen…',
    'all': 'Alle',
    'no_marks': 'Noch keine Anmerkungen',
    'page_n': 'Seite {n}',
    'theme_light': 'Hell',
    'theme_dark': 'Dunkel',
    'theme_paper': 'Papier',
    'theme_warm': 'Warm',
    'theme_green': 'Grün',
    'theme_blue': 'Blau',
  },
  'fr': {
    'err_access': "Impossible d'accéder à ce fichier",
    'untitled': 'Sans titre.md',
    'replace_title': 'Remplacer le fichier du même nom ?',
    'replace_msg': "Une entrée pour « {name} » existe déjà. Le contenu sera mis à jour, mais les anciennes annotations risquent d'être décalées.",
    'cancel': 'Annuler',
    'replace': 'Remplacer',
    'err_import': "Échec de l'importation",
    'err_gone': "Le fichier n'existe plus — retiré de la liste",
    'deleted': '« {name} » supprimé',
    'undo': 'Annuler',
    'del_title': 'Supprimer cette entrée ?',
    'del_msg': 'La copie dans l\'appli de « {name} » et ses annotations seront supprimées.',
    'delete': 'Supprimer',
    'clear_title': 'Effacer toutes les entrées ?',
    'clear_msg': "Toutes les copies dans l'appli et les annotations seront supprimées. Action irréversible.",
    'clear': 'Effacer',
    'cleared': 'Effacé',
    'home_tagline': 'Lisez confortablement les fichiers qui arrivent sur votre téléphone',
    'open_btn': 'Ouvrir un document',
    'empty_title': 'Aucun document pour le moment',
    'empty_hint': "Touchez le bouton ci-dessus pour choisir un fichier — ou ouvrez-les depuis WhatsApp, Telegram ou votre appli e-mail avec « Ouvrir avec MD+ ».",
    'recent': 'Récents',
    'built': 'compilé le',
    'err_docx_empty': "Aucun texte n'a pu être extrait de ce document",
    'err_epub': 'Impossible de lire ce fichier',
    'err_missing': "Le fichier n'existe pas ou est illisible",
    'err_encoding': 'Encodage de fichier inconnu',
    'err_open': 'Ouverture impossible — le fichier est peut-être corrompu ou dans un format non pris en charge',
    'chapter': 'Chapitre {n}',
    'no_outline_pdf': 'Ce PDF n\'a pas de signets (pas encore pris en charge par le moteur)',
    'no_outline': 'Ce document n\'a aucun titre pour la navigation',
    'outline': 'Sommaire',
    'search': 'Rechercher',
    'marks': 'Annotations',
    'font_smaller': 'Texte plus petit',
    'font_bigger': 'Texte plus grand',
    'theme_sheet': 'Arrière-plan',
    'search_hint': 'Rechercher dans le texte…',
    'prev': 'Précédent',
    'next': 'Suivant',
    'close_search': 'Fermer la recherche',
    'underline': 'Souligner',
    'highlight': 'Surligner',
    'copy': 'Copier',
    'copied': 'Copié',
    'marks_count': 'Annotations ({n})',
    'search_marks': 'Rechercher dans les annotations…',
    'all': 'Tout',
    'no_marks': "Aucune annotation pour l'instant",
    'page_n': 'Page {n}',
    'theme_light': 'Clair',
    'theme_dark': 'Sombre',
    'theme_paper': 'Papier',
    'theme_warm': 'Warm',
    'theme_green': 'Vert',
    'theme_blue': 'Bleu',
  },
};

var _lang = 'zh';

/// main() 里调用一次：按系统语言前缀选定文案语言，未支持的语言回退英文。
void initStrings(String systemLocale) {
  final l = systemLocale.toLowerCase();
  _lang = kStrings.keys.firstWhere((k) => l.startsWith(k), orElse: () => 'en');
}

String s(String key) => kStrings[_lang]?[key] ?? kStrings['en']?[key] ?? kStrings['zh']?[key] ?? key;
